[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/NCS/*"
  to = "/NCS/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
